import React from 'react';
import { createRoot } from 'react-dom/client';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import '@fontsource/space-grotesk/500.css';
import '@fontsource/space-grotesk/600.css';
import '@fontsource/space-grotesk/700.css';
import App from './app/App';
const root=document.getElementById('root');
if(!root)throw new Error('Missing root');
createRoot(root).render(<React.StrictMode><App/></React.StrictMode>);
